/*
 * Luis David Vidales Ramirez 183060
 * Universidad Politecnica de San Luis Potosi
 */
package GUI;
//GIL, FRANKIL

import BaseDeDatos.ClienteLBD;
import BaseDeDatos.PedidoLBD;
import GUI_Admin.AgregaEmpleado1;
import GUI_Admin.ConsultaEmplado;
import GUI_Admin.EliminaEmpleado;
import GUI_Admin.ModificaEmpleado;
import java.io.IOException;
import static java.lang.System.exit;
import javax.swing.JOptionPane;
import reportes.Sincronizado;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import reportes.clientePdf;
import reportes.pedidoGrafico;

/**
 * Frame con opciones de Administrador
 * @author Luis David Vidales Ramírez, 183060
 */
public class Administrador1 extends javax.swing.JFrame {
private Connection con;
    /**
     * Creates new form Menu
     * @param con Conexión
     */
    public Administrador1(Connection con) {
        this.con=con;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCA = new javax.swing.JButton();
        btnME = new javax.swing.JButton();
        btnAE = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnRegresar1 = new javax.swing.JButton();
        btnEE = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(280, 100));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logop.jpg"))); // NOI18N
        jLabel1.setText("labelLogo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 40, 50, 30);

        f.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        f.setText("Bienvenido Administrador");
        jPanel1.add(f);
        f.setBounds(190, 90, 200, 30);

        btnTerminar.setBackground(new java.awt.Color(229, 229, 229));
        btnTerminar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnTerminar.setText("Terminar Programa");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnTerminar);
        btnTerminar.setBounds(420, 270, 130, 22);

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel3.setText("Almacén PoliLinea");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 40, 140, 30);

        btnCA.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnCA.setText("Consulta de Empleados");
        btnCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAActionPerformed(evt);
            }
        });
        jPanel1.add(btnCA);
        btnCA.setBounds(20, 200, 180, 40);

        btnME.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnME.setText("Modifica Empleado");
        btnME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEActionPerformed(evt);
            }
        });
        jPanel1.add(btnME);
        btnME.setBounds(230, 140, 160, 40);

        btnAE.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnAE.setText("Agregar Empleado");
        btnAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAEActionPerformed(evt);
            }
        });
        jPanel1.add(btnAE);
        btnAE.setBounds(20, 140, 180, 40);

        btnReportes.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnReportes.setText("Consultar Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportes);
        btnReportes.setBounds(230, 200, 160, 40);

        btnRegresar1.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnRegresar1.setText("Cerrar Sesión");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar1);
        btnRegresar1.setBounds(230, 260, 160, 40);

        btnEE.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnEE.setText("Elimina Empleado");
        btnEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEEActionPerformed(evt);
            }
        });
        jPanel1.add(btnEE);
        btnEE.setBounds(20, 260, 180, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 570, 330);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/og.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 590, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"El programa se cerrara :)");
           exit(0);
           
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        PedidoLBD lista= new PedidoLBD(con);
        lista.crearLista();
        pedidoGrafico grafa= new pedidoGrafico(lista);
    try {
        grafa.crearGrafico("grafico.pdf");
    } catch (IOException ex) {
        Logger.getLogger(Administrador1.class.getName()).log(Level.SEVERE, null, ex);
    }
          ClienteLBD listac= new ClienteLBD(con);
        listac.crearLista();
        clientePdf graf= new clientePdf(listac);
        graf.pdfPersona("cliente.pdf");
       Thread hilo1= new Thread(new Sincronizado("grafico.pdf"),"Grafica");
       Thread hilo2= new Thread(new Sincronizado("cliente.pdf"),"Cliente");
       Thread hilo3= new Thread(new Sincronizado("loginsexitosos.pdf"),"LoginEpdf");
       Thread hilo4= new Thread(new Sincronizado("loginsfallidos.pdf"),"LoginFpdf");
       Thread hilo5= new Thread(new Sincronizado("loginsexitosos.xls"),"LoginFxls");
       Thread hilo6= new Thread(new Sincronizado("loginsfallidos.xls"),"LoginFxls");
       hilo1.setPriority(Thread.MAX_PRIORITY);
        hilo2.setPriority(Thread.MAX_PRIORITY);
         hilo3.setPriority(Thread.MAX_PRIORITY);
          hilo4.setPriority(Thread.MAX_PRIORITY);
           hilo5.setPriority(Thread.MAX_PRIORITY);
            hilo6.setPriority(Thread.MAX_PRIORITY);
      hilo1.start();
      hilo2.start();
      hilo3.start();
      hilo4.start();
      hilo5.start();
      hilo6.start();
      
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // ELBUENO
       
        Menu menu= new Menu();
        menu.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAEActionPerformed
        // TODO add your handling code here:
      AgregaEmpleado1 ag;
    try {
        ag = new AgregaEmpleado1(con);
           ag.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(Administrador1.class.getName()).log(Level.SEVERE, null, ex);
    }
   

    }//GEN-LAST:event_btnAEActionPerformed

    private void btnMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEActionPerformed
        // TODO add your handling code here:
           ModificaEmpleado ag;
    try {
        ag = new ModificaEmpleado(con);
           ag.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(Administrador1.class.getName()).log(Level.SEVERE, null, ex);
    }
       
    }//GEN-LAST:event_btnMEActionPerformed

    private void btnCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAActionPerformed
         ConsultaEmplado ag;
    try {
        ag = new ConsultaEmplado(con);
           ag.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(Administrador1.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnCAActionPerformed

    private void btnEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEEActionPerformed
        // TODO add your handling code here:
              EliminaEmpleado ag;
    try {
        ag = new EliminaEmpleado(con);
           ag.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(Administrador1.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnEEActionPerformed

    /**
     * metodo run
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
/**
 * Variables de instancia
 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAE;
    private javax.swing.JButton btnCA;
    private javax.swing.JButton btnEE;
    private javax.swing.JButton btnME;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLabel f;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
