/*
 * Luis David Vidales Ramirez 183060
 * Universidad Politecnica de San Luis Potosi
 */
package GUI;
//GIL, FRANKIL


import BaseDeDatos.ConsultaPedidoTabla;
import BaseDeDatos.ConsultaPedidoTablaBus;
import BaseDeDatos.Funciones;
import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *Frame para consultar pedidos
 * @author Luis David Vidales Ramírez, 183060
 */
public class ConsultaPedido extends javax.swing.JFrame {
   private  ConsultaPedidoTabla obj;
    private  ConsultaPedidoTablaBus obj2;
  private final Connection con;
    private Funciones func= new Funciones();
    /**
     * Consultar Pedido
     * Creates new form Menu
     */
    /**
     * Constructor 
     * @param con Conexión
     * @throws SQLException  Puede lanzar excepciones SQL 
     */
    public ConsultaPedido(Connection con) throws SQLException {
        this.con=con;
         obj=new ConsultaPedidoTabla(con);
          initComponents();
            func.comboId(con, "pedido", "idPedido", comboId);
       
           this.tabla.setModel(obj.getModelo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnConsultarId = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRegresar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        radioActivos = new javax.swing.JRadioButton();
        radioEntregados = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        comboId = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(280, 100));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logop.jpg"))); // NOI18N
        jLabel1.setText("labelLogo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 30, 50, 30);

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 200, 20, 20);

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel3.setText("Almacén PoliLinea");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(400, 30, 140, 30);

        btnConsultarId.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnConsultarId.setText("Consultar por ID");
        btnConsultarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarIdActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarId);
        btnConsultarId.setBounds(10, 240, 120, 30);

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel6.setText("Consulta de Pedidos");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 30, 170, 30);

        btnRegresar2.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnRegresar2.setText("Regresar");
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar2);
        btnRegresar2.setBounds(20, 300, 90, 30);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pedido", "Estado", "Total", "ID Cliente"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 90, 390, 220);

        buttonGroup1.add(radioActivos);
        radioActivos.setText("Activos");
        radioActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioActivosActionPerformed(evt);
            }
        });
        jPanel1.add(radioActivos);
        radioActivos.setBounds(20, 120, 62, 21);

        buttonGroup1.add(radioEntregados);
        radioEntregados.setText("Entregados");
        radioEntregados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEntregadosActionPerformed(evt);
            }
        });
        jPanel1.add(radioEntregados);
        radioEntregados.setBounds(20, 150, 90, 21);

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel5.setText("Por Estado");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 80, 70, 30);

        comboId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIdActionPerformed(evt);
            }
        });
        jPanel1.add(comboId);
        comboId.setBounds(50, 192, 50, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 570, 340);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/og.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 590, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarIdActionPerformed
        // 
       try{
         Statement sts=con.createStatement();
         sts.execute("Select * from pedido where idPedido='"+comboId.getSelectedItem()+"'");
            System.out.println("Select * from pedido where idPedido='"+comboId.getSelectedItem()+"'");
         ResultSet rs= sts.getResultSet();
        
         String cadena="";
            if(rs.next()){
                 cadena="Id del Pedido: "+rs.getString("idPedido")+
                         "\nEstado: "+rs.getString("estado")+
                         "\nTotal: "+rs.getString("total")+
                         "\nId Cliente: "+rs.getString("idCliente");
            System.out.println(cadena);
         JOptionPane.showMessageDialog(null, cadena);
            }else{
                  JOptionPane.showMessageDialog(null, "No existe pedido con tal id");
            }
        
            
         
     }catch(SQLException ex){
         System.out.println(ex.getNextException());
     }
        try {
          obj=new ConsultaPedidoTabla(con);
      } catch (SQLException exp) {
          Logger.getLogger(EliminaCliente.class.getName()).log(Level.SEVERE, null, exp);
      }
          tabla.setModel(obj.getModelo());
    }//GEN-LAST:event_btnConsultarIdActionPerformed

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
    }//GEN-LAST:event_btnRegresar2ActionPerformed

    private void comboIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboIdActionPerformed

    private void radioActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioActivosActionPerformed
        // TODO add your handling code here:
         try {
          obj2=new ConsultaPedidoTablaBus(con,"Activo");
      } catch (SQLException exp) {
          Logger.getLogger(EliminaCliente.class.getName()).log(Level.SEVERE, null, exp);
      }
          tabla.setModel(obj2.getModelo());
    }//GEN-LAST:event_radioActivosActionPerformed

    private void radioEntregadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEntregadosActionPerformed
        // TODO add your handling code here:
           try {
          obj2=new ConsultaPedidoTablaBus(con,"Entregado");
      } catch (SQLException exp) {
          Logger.getLogger(EliminaCliente.class.getName()).log(Level.SEVERE, null, exp);
      }
          tabla.setModel(obj2.getModelo());    
    }//GEN-LAST:event_radioEntregadosActionPerformed

    /**
     * Metodo run
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarId;
    private javax.swing.JButton btnRegresar2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioActivos;
    private javax.swing.JRadioButton radioEntregados;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
