/*
 * Luis David Vidales Ramirez 183060
 * Universidad Politecnica de San Luis Potosi
 */
package GUI;
//GIL, FRANKIL

import BaseDeDatos.Conexion;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logins.Reportes;
import static logins.Reportes.login;
import logins.logins;
import logins.loginsLBD;
import logins.loginspdf;

/**
 *Frame principal
 * @author Luis David Vidales Ramírez, 183060
 */
public class Menu extends javax.swing.JFrame {
    Conexion conexion= new Conexion();
    Connection con= conexion.conectar();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnInicia = new javax.swing.JButton();

        setLocation(new java.awt.Point(280, 100));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logop.jpg"))); // NOI18N
        jLabel1.setText("labelLogo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 40, 50, 30);

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/og.jpg"))); // NOI18N
        jPanel1.add(labelFondo);
        labelFondo.setBounds(0, 0, 300, 400);

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel2.setText("Almacén PoliLinea");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(400, 40, 140, 30);

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel3.setText("Inicia Sesión");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 110, 100, 30);

        txtPass.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.add(txtPass);
        txtPass.setBounds(380, 260, 160, 22);

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 230, 60, 15);

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel5.setText("Usuario");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(380, 160, 40, 15);

        txtUser.setBackground(new java.awt.Color(238, 238, 238));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jPanel1.add(txtUser);
        txtUser.setBounds(380, 190, 160, 22);

        btnInicia.setText("Inicia Sesión");
        btnInicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicia);
        btnInicia.setBounds(410, 320, 110, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaActionPerformed
        // TODO add your handling code here:
  
        
        String pass="";
        String user="";
        user=txtUser.getText();
        pass=txtPass.getText();
        if(pass.isBlank() || user.isBlank()){
            JOptionPane.showMessageDialog(null,"Debes llenar todos los campos");
        }else{
            try{
               login(con,user,pass);
            
        
             
        }catch(FileNotFoundException | logins ex){
            System.out.println("--->"+ex);
            System.out.println(ex.toString());
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

        loginsLBD listae= new loginsLBD(con);
         loginsLBD listaf= new loginsLBD(con);
        listae.listaExitosa();
        listae.imprimeIterator();
        System.out.println("fsfsdfsdfsf\n");
        listaf.listaFallida();
        listaf.imprimeIterator();
        
        loginspdf pdf= new loginspdf(listae);
        pdf.pdfLogins("loginsexitosos.pdf",1);
          loginspdf pdf2= new loginspdf(listaf);
        pdf2.pdfLogins("loginsfallidos.pdf",0);
          this.setVisible(false);
        }
         
     
        
    }//GEN-LAST:event_btnIniciaActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    /**
     * Metodo run
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
