/*
 * Luis David Vidales Ramirez 183060
 * Universidad Politecnica de San Luis Potosi
 */
package GUI;
//GIL, FRANKIL

import static java.lang.System.exit;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *Frame Principal con las operaciones de usuario tipo Empleado
 * @author Luis David Vidales Ramírez, 183060
 */
public class Principal1 extends javax.swing.JFrame {
private Connection con;
    /**
     * Form Principal para usuarios tipo Empleado
     * Creates new form Menu
     */
/**
 * Constructor
 * @param con  Conexión
 */
    public Principal1(Connection con) {
        this.con=con;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JButton();
        btnRE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCC = new javax.swing.JButton();
        btnMC = new javax.swing.JButton();
        btnRC = new javax.swing.JButton();
        btnCP = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnEM = new javax.swing.JButton();
        btnAP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(280, 100));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logop.jpg"))); // NOI18N
        jLabel1.setText("labelLogo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 40, 50, 30);

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel2.setText("Bienvenido, selecciona la opción deseada");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 100, 250, 30);

        btnTerminar.setBackground(new java.awt.Color(229, 229, 229));
        btnTerminar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnTerminar.setText("Terminar Programa");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnTerminar);
        btnTerminar.setBounds(420, 300, 130, 22);

        btnRE.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnRE.setText("Registrar Entrega");
        btnRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREActionPerformed(evt);
            }
        });
        jPanel1.add(btnRE);
        btnRE.setBounds(230, 290, 160, 40);

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel3.setText("Almacén PoliLinea");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 40, 140, 30);

        btnCC.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnCC.setText("Consulta de Clientes");
        btnCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCCActionPerformed(evt);
            }
        });
        jPanel1.add(btnCC);
        btnCC.setBounds(30, 150, 160, 40);

        btnMC.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnMC.setText("Modifica Cliente");
        btnMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCActionPerformed(evt);
            }
        });
        jPanel1.add(btnMC);
        btnMC.setBounds(30, 300, 160, 40);

        btnRC.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnRC.setText("Registrar Cliente");
        btnRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRCActionPerformed(evt);
            }
        });
        jPanel1.add(btnRC);
        btnRC.setBounds(30, 200, 160, 40);

        btnCP.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnCP.setText("Consultar Pedido");
        btnCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPActionPerformed(evt);
            }
        });
        jPanel1.add(btnCP);
        btnCP.setBounds(230, 150, 160, 40);

        btnCerrar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar);
        btnCerrar.setBounds(430, 150, 110, 30);

        btnEM.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnEM.setText("Elimina Cliente");
        btnEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEMActionPerformed(evt);
            }
        });
        jPanel1.add(btnEM);
        btnEM.setBounds(30, 250, 160, 40);

        btnAP.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnAP.setText("Agregar Pedido");
        btnAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAPActionPerformed(evt);
            }
        });
        jPanel1.add(btnAP);
        btnAP.setBounds(230, 220, 160, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 570, 350);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/og.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 590, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"El programa se cerrara :)");
           exit(0);
           
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // ELBUENO
      this.setVisible(false);
      Menu menu= new Menu();
      menu.setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCCActionPerformed
        ConsultaCliente ca = null;
    try {
        ca = new ConsultaCliente(con);
          ca.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(Principal1.class.getName()).log(Level.SEVERE, null, ex);
    }
      
    }//GEN-LAST:event_btnCCActionPerformed

    private void btnRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRCActionPerformed
        RegistroCliente1 re;
    try {
        re = new RegistroCliente1(con);
         re.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(Principal1.class.getName()).log(Level.SEVERE, null, ex);
    }
       
        
        
    }//GEN-LAST:event_btnRCActionPerformed

    private void btnMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCActionPerformed

        // TODO add your handling code here:
         

           ModificaCliente a;
    try {
        a = new ModificaCliente(con);
         a.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(Principal1.class.getName()).log(Level.SEVERE, null, ex);
    }
           
        
    
    }//GEN-LAST:event_btnMCActionPerformed

    private void btnCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPActionPerformed
        // TODO add your handling code here:
      
        ConsultaPedido consulta;
    try {
        consulta = new ConsultaPedido(con);
            consulta.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(Principal1.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_btnCPActionPerformed

    private void btnREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREActionPerformed
        // TODO add your handling code here:
        RegistroEntrega reg;
    try {
        reg = new RegistroEntrega(con);
           reg.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(Principal1.class.getName()).log(Level.SEVERE, null, ex);
    }
     
    }//GEN-LAST:event_btnREActionPerformed

    private void btnEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEMActionPerformed
    try {
        // TODO add your handling code here:
        EliminaCliente em= new EliminaCliente(con);
        em.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(Principal1.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_btnEMActionPerformed

    private void btnAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAPActionPerformed
        // TODO add your handling code here:
        AgregaPedido ap;
    try {
        ap = new AgregaPedido(con);
          ap.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(Principal1.class.getName()).log(Level.SEVERE, null, ex);
    }
      
        
    }//GEN-LAST:event_btnAPActionPerformed
    
  
    /**
     * Metodo run
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAP;
    private javax.swing.JButton btnCC;
    private javax.swing.JButton btnCP;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEM;
    private javax.swing.JButton btnMC;
    private javax.swing.JButton btnRC;
    private javax.swing.JButton btnRE;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
