/*
 * Luis David Vidales Ramirez 183060
 * Universidad Politecnica de San Luis Potosi
 */
package GUI_Admin;
//GIL, FRANKIL

import BaseDeDatos.ConsultaUsuarioTabla;
import BaseDeDatos.Funciones;
import GUI.*;
import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *Frame para agregar empleados
 * @author Luis David Vidales Ramírez, 183060
 */
public class AgregaEmpleado1 extends javax.swing.JFrame {
private final Connection con;
private ConsultaUsuarioTabla obj;
    /**
     * AgregEmple<do
     * Creates new form Menu
     */
/**
 * Constructor
 * @param con Conexión
 * @throws SQLException Puede lanzar excepciones SQL
 */
    public AgregaEmpleado1(Connection con)throws SQLException {
        this.con=con;
          obj=new ConsultaUsuarioTabla(con);
        initComponents();
          this.tabla.setModel(obj.getModelo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrarCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        combotipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(280, 100));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logop.jpg"))); // NOI18N
        jLabel1.setText("labelLogo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 30, 50, 30);

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel3.setText("Almacén PoliLinea");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 30, 140, 30);

        btnRegistrarCliente.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnRegistrarCliente.setText("Agregar");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarCliente);
        btnRegistrarCliente.setBounds(50, 300, 100, 30);

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel6.setText("Registro de Empleado");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 30, 170, 30);

        btnRegresar.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar);
        btnRegresar.setBounds(230, 30, 90, 30);

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel7.setText("Tipo de usuario");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 240, 120, 30);

        txtuser.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.add(txtuser);
        txtuser.setBounds(40, 130, 120, 22);

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 170, 120, 30);

        txtpass.setBackground(new java.awt.Color(238, 238, 238));
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        jPanel1.add(txtpass);
        txtpass.setBounds(40, 210, 120, 22);

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel10.setText("Nombre de Usuario");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 90, 120, 30);

        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Administrador" }));
        jPanel1.add(combotipo);
        combotipo.setBounds(40, 270, 110, 22);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Cliente", "Nombre", "Teléfono", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 90, 360, 220);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 570, 340);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/og.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 590, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        // ELBUENO
        String usuario=txtuser.getText();
        String contra=txtpass.getText();
       int tipo=combotipo.getSelectedIndex();
       Funciones compara= new Funciones();
       boolean comp=false;
       if(usuario.isBlank() || contra.isBlank()){
                JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        }else{
    try {
        comp = compara.compararIguales(con, "user", usuario, "usuarios");
    } catch (SQLException ex) {
        Logger.getLogger(AgregaEmpleado1.class.getName()).log(Level.SEVERE, null, ex);
    }
        String registro="insert into usuarios (user,pass, tipo) VALUES('"
                          +usuario+"','"+contra+"','"+tipo+"')";
        if(!comp){
            
            
                if(usuario.length()>15 || contra.length()>15){
                     JOptionPane.showMessageDialog(null, "El usuario y la contraseña no deben exceder los 15 caracteres");
                }else{
                    try{
                    System.out.println("denrtro de try comp true registro"+registro  );
                Statement insertar = con.createStatement();
                    insertar.executeUpdate(registro);
                     JOptionPane.showMessageDialog(null, "Usuario Registrado Exitosamente");

                  }catch(SQLException ex){
                      System.out.println(ex.getNextException());

                         JOptionPane.showMessageDialog(null, "No se pudo generar el registro");
                      }   
                }
                
           }
        else{
             System.out.println("denrtro de try comp false registro"+registro  );
              JOptionPane.showMessageDialog(null, "Usuario ya existente");
        }
         try {
          obj=new ConsultaUsuarioTabla(con);
      } catch (SQLException exp) {
          Logger.getLogger(EliminaCliente.class.getName()).log(Level.SEVERE, null, exp);
      }
          tabla.setModel(obj.getModelo());
       }
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
           
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    /**
     * Metodo run
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
